### ISSUE TITLE
Save project with visualparent

### ISSUE THREAD

**Issue by tokejepsen** [getavalon/core#325]
**Problem**

When having visualparent on assets the saving process errors.

State of inventory when loading project:
```toml
[[shots]]
label = "ep0010"
group = "Episode"
name = "ep0010"

[[shots]]
label = "sq0010"
group = "Sequence"
visualParent = 5b3dd2c0cd5f4c097c405697
name = "ep0010_sq0010"

[[shots]]
label = "sh0010"
group = "Shot"
visualParent = 5b3dd2c0cd5f4c097c405699
name = "ep0010_sq0010_sh0010"
```

Error message when ```python -m avalon.inventory --save```:
```
invalid literal for int() with base 10: '5b3dd2c0cd5f4c097c405697'
```
