### ISSUE TITLE
The `visualParent` attribute will break Avalon from saving .inventory.toml

### ISSUE THREAD

**Issue by davidlatwe** [getavalon/core#347]
### Problem

In your `.inventory.toml`, if you adding the attribute `group` for grouping assets visually in Launcher, 
like this
```toml
[[films]]
label = "S001"
group = "Shots"
tasks = [ "animate", "layout",]
name = "Shots_S001"
```
After saving this with `$ avalon --save`, there will be an extra attribute `visualParent` which content the visual parent's `ObjectID` write into database.

Now if you load them back from database with `$ avalon --load`, the `.inventory.toml` will be like
```toml
[[films]]
label = "S001"
visualParent = 5ba1f78fed9f0d812c2f9484
group = "Shots"
tasks = [ "animate", "layout",]
name = "Shots_S001"
```
Then when you save it again with `$ avalon --save`, this error will pop-up in your terminal
```
could not convert string to float: '5ba1f78fed9f0d812c2f9484'
```

**Comment by mottosso** [comment]
Thanks @davidlatwe. :) What happens if you edit that toml, and put the parent in quotes?

```toml
[[films]]
visualParent = "5ba1f78fed9f0d812c2f9484"
```

It may work, but I think we might also need to actually convert it to a Mongo ID.
